-- MySQL Script generated by MySQL Workbench
-- Thu May 13 10:21:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Viaticos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Viaticos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Viaticos` DEFAULT CHARACTER SET utf8 ;
USE `Viaticos` ;

-- -----------------------------------------------------
-- Table `Viaticos`.`Perfiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Viaticos`.`Perfiles` ;

CREATE TABLE IF NOT EXISTS `Viaticos`.`Perfiles` (
  `idPerfiles` INT NOT NULL,
  `DescripcionPerfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfiles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viaticos`.`Areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Viaticos`.`Areas` ;

CREATE TABLE IF NOT EXISTS `Viaticos`.`Areas` (
  `idAreas` INT NOT NULL,
  `DescripcionArea` VARCHAR(45) NOT NULL,
  `PresupuestoTransporte` DECIMAL(11,4) NULL,
  `PresupuestoViatico` DECIMAL(11,4) NULL,
  PRIMARY KEY (`idAreas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viaticos`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Viaticos`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `Viaticos`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `NombreEmp` VARCHAR(40) NOT NULL,
  `ApellidoEmp` VARCHAR(40) NULL,
  `TelefonoEmp` VARCHAR(10) NULL,
  `CorreoEmp` VARCHAR(45) NOT NULL,
  `ContraseñaEmp` VARCHAR(8) NOT NULL,
  `Perfiles_idPerfiles` INT NOT NULL,
  `Areas_idAreas` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Perfiles_idx` (`Perfiles_idPerfiles` ASC) VISIBLE,
  INDEX `fk_Empleado_Areas1_idx` (`Areas_idAreas` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Perfiles`
    FOREIGN KEY (`Perfiles_idPerfiles`)
    REFERENCES `Viaticos`.`Perfiles` (`idPerfiles`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empleado_Areas1`
    FOREIGN KEY (`Areas_idAreas`)
    REFERENCES `Viaticos`.`Areas` (`idAreas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viaticos`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Viaticos`.`Factura` ;

CREATE TABLE IF NOT EXISTS `Viaticos`.`Factura` (
  `idFactura` INT NOT NULL,
  `DescripcionFactura` VARCHAR(45) NULL,
  `FechaEmision` VARCHAR(45) NULL,
  `MontoFactura` DECIMAL(11,4) NOT NULL,
  PRIMARY KEY (`idFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viaticos`.`Comision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Viaticos`.`Comision` ;

CREATE TABLE IF NOT EXISTS `Viaticos`.`Comision` (
  `idComision` INT NOT NULL,
  `TipoComision` VARCHAR(45) NOT NULL,
  `ComisionAprobada` TINYINT NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `Factura_idFactura` INT NOT NULL,
  PRIMARY KEY (`idComision`),
  INDEX `fk_Comision_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Comision_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `Viaticos`.`Factura` (`idFactura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Viaticos`.`Empleado_has_Comision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Viaticos`.`Empleado_has_Comision` ;

CREATE TABLE IF NOT EXISTS `Viaticos`.`Empleado_has_Comision` (
  `Empleado_idEmpleado` INT NOT NULL,
  `Comision_idComision` INT NOT NULL,
  INDEX `fk_Empleado_has_Comision_Comision1_idx` (`Comision_idComision` ASC) VISIBLE,
  INDEX `fk_Empleado_has_Comision_Empleado1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_Comision_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Viaticos`.`Empleado` (`idEmpleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empleado_has_Comision_Comision1`
    FOREIGN KEY (`Comision_idComision`)
    REFERENCES `Viaticos`.`Comision` (`idComision`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


DROP PROCEDURE IF EXISTS `proc_insert_empleado`;
DELIMITER ;;
CREATE PROCEDURE `proc_insert_empleado` (
pidEmpleado int, 
pNombreEmp varchar(40),
pApellidoEmp varchar(40), 
pTelefonoEmp varchar(10),
pCorreoEmp varchar(45),
pContraseñaEmp varchar(8), 
pPerfiles_idPerfiles int,
pAreas_idAreas int
)
BEGIN
INSERT INTO Empleado (idEmpleado, NombreEmp, ApellidoEmp, TelefonoEmp, CorreoEmp, ContraseñaEmp, 
Perfiles_idPerfiles, Areas_idAreas) VALUES (pidEmpleado, pNombreEmp, pApellidoEmp, pTelefonoEmp, pCorreoEmp, 
pContraseñaEmp, pPerfiles_idPerfiles, pAreas_idAreas);
END ;;
DELIMITER ; 